### ISSUE TITLE
Ecessive Any State

### ISSUE THREAD

**Issue by Fynn9563** [hai-vr/combo-gesture-expressions-av3#328] opened 2022-03-26 09:37 UTC
![image](https://user-images.githubusercontent.com/68993521/160233698-cf46de6f-b42a-4acd-b1e4-200a31f6862b.png)
Is there a way you can reduce the amount of Any States used?

**Comment by hai-vr** [comment] 2022-03-26 18:36
Maybe in ComboGestureExpressions V2, definitely not in ComboGestureExpressions V1.

The problem is that avoiding Any State or idle states with lots of transitions is easy with Write Defaults OFF, but hard with Write Defaults ON. I could easily achieve this if I force everyone to use Write Defaults OFF, but this would cause a *lot* of compatibility issues with people's avatars.

The alternative way I've found to use Write Defaults ON without these problematic transitions is to use a complex blend tree, which is what I'm looking to try doing in ComboGestureExpressions V2.

**Comment by hai-vr** [comment] 2022-03-26 19:15
Actually I'm discussing this issue with other people knowledgable with animators, there may be a way. If anything it will be in CGE V2.

**Comment by hai-vr** [comment] 2022-05-01 00:55
Will be fixed in CGE V1.6 using sub state machines
![Unity_2022-05-01_01-17-25_AMa26J2Gfo](https://user-images.githubusercontent.com/60819407/166127589-b90d32ed-dbab-4b05-96dd-7c344ebd5b55.png)
![sx_2022-05-01_01-18-37_qlFt9ClWdX](https://user-images.githubusercontent.com/60819407/166127592-d0c0fdb2-cbf1-4dec-bd5a-1f97b5b6644f.png)

![sx_2022-05-01_01-17-56_zw3jsYyFly](https://user-images.githubusercontent.com/60819407/166127591-646868ac-ffbb-41bd-8560-d8ef49b21aa3.png)

s

**Comment by hai-vr** [comment] 2022-05-05 21:34
Done

**Closed by hai-vr** 2022-05-05 21:34 UTC
Labels: feature, high-priority
